### ISSUE TITLE
Integrations are available but no roms

### ISSUE THREAD

**Issue by stanzelot** [Riku55/galaxy-integration-n64-RetroArch-#3]
I have a problem with the retro arch integrations.
When I connect, the folders are there but completely empty. I did everything as mentioned in the readme.
![001](https://user-images.githubusercontent.com/56726718/76160188-460c0380-6128-11ea-916c-bdb23298517e.png)
![002](https://user-images.githubusercontent.com/56726718/76160192-4a382100-6128-11ea-8db0-7cc8323efe65.png)

**Comment by riku55** [comment]
You need to also add a / at the end of each path, so it ends with ROMS/ and BIN/.

I should probably change this so it just takes the path with or without / in the end. I was hoping to get rid of the problem when making a gui anyway, but ain't nobody got time for that (or anything else). But I might just add this in a few lines.

**Comment by stanzelot** [comment]
Thanks for the advice but unfortunately that did not work for me. The folders are still empty :(

I now redid every step you mentioned in the description but still there are no roms. Any other suggestion? Please help.

**Comment by riku55** [comment]
Sorry for the late answer. Though I just realized that you're using not my integration but the forked one by jshackles. So you would need to ask him about help with anything but the n64 integration which is the one I did. Though he didn't enable issues in his fork. So try contacting jshackles and ask about your problem and mention that issues aren't turned on in his fork.

**Comment by stanzelot** [comment]
Thank you for your clarification :)
I have contacted Jason and told him about the missing issue in his fork and my problem.
Waiting for his response.

**Comment by ahnernoch** [comment]
I have the same problem with you integration. It does not show any rom. What Retroarch you use? does it matter 32 or 64 bit? Can't get it work to show any Rom. 

![git](https://user-images.githubusercontent.com/10847489/78324461-24e1db80-754b-11ea-959c-35b1c193708e.png)

![retro](https://user-images.githubusercontent.com/10847489/78324471-2ca18000-754b-11ea-9bc7-7a5995d7afe7.png)
![n64](https://user-images.githubusercontent.com/10847489/78324472-2d3a1680-754b-11ea-9aa9-df6969124923.png)
![gog](https://user-images.githubusercontent.com/10847489/78324473-2dd2ad00-754b-11ea-8457-32887bf6c957.png)

**Comment by riku55** [comment]
Closed and made a new issue as the problem here was using another integration.

**Comment by ahnernoch** [comment]
Alright.

 

Von: Riku55 <notifications@github.com> 
Gesendet: Freitag, 3. April 2020 12:13
An: Riku55/galaxy-integration-n64-RetroArch- <galaxy-integration-n64-RetroArch-@noreply.github.com>
Cc: ahnernoch <guthpascal@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [Riku55/galaxy-integration-n64-RetroArch-] Integrations are available but no roms (#3)

 

Next time better make a new
